// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggqnrouqyvxjumxxrvjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdncW5yb3VxeXZ4anVteHhydmpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MDIyNjUsImV4cCI6MjA2NjQ3ODI2NX0.gNXN-OFVMa-UXAepgot8_u7tcuoK-Dw6ZulX3l1m7Hs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);